---

_You are currently looking at **version 1.5** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 3 - More Pandas
This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

### Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries.*

In [137]:
import numpy as np
import pandas as pd
df = pd.read_excel('Energy Indicators.xls')

In [138]:
df

,Unnamed: 0,Unnamed: 1,Environmental Indicators: Energy,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Energy Supply and Renewable Electricity Produc...,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,Last update: December 2015
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,Choose a country from the following drop-down ...,NaN,NaN,Andorra
6,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,Country,Energy Supply,Energy Supply per capita,Renewable Electricity Production
8,NaN,NaN,NaN,Petajoules,Gigajoules,%
9,NaN,NaN,Andorra,9,121,88.6957
10,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,website: http://unstats.un.org/unsd/ENVIRONMEN...
12,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,Energy Supply,Energy Supply per capita,Renewable Electricity Production
15,NaN,NaN,NaN,Petajoules,Gigajoules,%
16,NaN,Afghanistan,Afghanistan,321,10,78.6693
17,NaN,Albania,Albania,102,35,100
18,NaN,Algeria,Algeria,1959,51,0.55101
19,NaN,American Samoa,American Samoa,...,...,0.641026
20,NaN,Andorra,Andorra,9,121,88.6957
21,NaN,Angola,Angola,642,27,70.9091
22,NaN,Anguilla,Anguilla,2,136,0
23,NaN,Antigua and Barbuda,Antigua and Barbuda,8,84,0
24,NaN,Argentina,Argentina,3378,79,24.0645
25,NaN,Armenia,Armenia,143,48,28.2361
26,NaN,Aruba,Aruba,12,120,14.8707
27,NaN,Australia,Australia1,5386,231,11.8108
28,NaN,Austria,Austria,1391,164,72.4528
29,NaN,Azerbaijan,Azerbaijan,567,60,6.38434
...,...,...,...,...,...,...
251,NaN,2,Data exclude Hong Kong and Macao Special Admin...,NaN,NaN,NaN
252,NaN,3,Data on kerosene-type jet fuel include aviatio...,NaN,NaN,NaN
253,NaN,4,"For confidentiality reasons, data on coal and ...",NaN,NaN,NaN
254,NaN,5,Data exclude Greenland and the Danish Faroes.,NaN,NaN,NaN
255,NaN,6,"Data include Monaco, and exclude the following...",NaN,NaN,NaN
256,NaN,7,Data for kerosene-type jet fuel include other ...,NaN,NaN,NaN
257,NaN,8,Data include Timor-Leste until 2001.,NaN,NaN,NaN
258,NaN,9,Data include San Marino and the Holy See.,NaN,NaN,NaN
259,NaN,10,Data include Okinawa.,NaN,NaN,NaN
260,NaN,11,The data for crude oil production include 50 p...,NaN,NaN,NaN
261,NaN,12,Data exclude Suriname and the Netherlands Anti...,NaN,NaN,NaN
262,NaN,13,Data include the Azores and Madeira.,NaN,NaN,NaN
263,NaN,14,Data for crude oil production include 50 per c...,NaN,NaN,NaN
264,NaN,15,Data exclude Kosovo from 2000 onwards.,NaN,NaN,NaN
265,NaN,16,Data include the Canary Islands.,NaN,NaN,NaN
266,NaN,17,Data include Liechtenstein for oil statistics.,NaN,NaN,NaN
267,NaN,18,"For confidentiality reasons, data on the follo...",NaN,NaN,NaN
268,NaN,19,"Shipments of coal and oil to Jersey, Guernsey ...",NaN,NaN,NaN
269,NaN,20,Includes the 50 states and the District of Col...,NaN,NaN,NaN
270,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,Definitions & Technical notes:,NaN,NaN,NaN,NaN
272,NaN,The data on energy supply and renewable electr...,NaN,NaN,NaN,NaN
273,NaN,Energy supply is defined as energy production ...,NaN,NaN,NaN,NaN
274,NaN,Electricity production refers to gross product...,NaN,NaN,NaN,NaN
275,NaN,Renewable electricity production (%) refers to...,NaN,NaN,NaN,NaN
276,NaN,… denotes no data available.,NaN,NaN,NaN,NaN
277,NaN,NaN,NaN,NaN,NaN,NaN
278,NaN,Data Quality:,NaN,NaN,NaN,NaN
279,NaN,The data are compiled primarily from the annua...,NaN,NaN,NaN,NaN
280,NaN,"For more information, visit http://unstats.un....",NaN,NaN,NaN,NaN

In [139]:
df = df.rename(columns = {'Environmental Indicators: Energy': 'Country', 'Unnamed: 3': 'Energy Supply', 'Unnamed: 4': 'Energy Supply per Capita', 'Unnamed: 5': '% Renewable'})

In [140]:
energy = df[['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']]

In [141]:
energy = energy[16:243]

In [142]:
energy.loc[:, 'Energy Supply'] = energy['Energy Supply']*1000000
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
16,Afghanistan,321000000,10,78.6693
17,Albania,102000000,35,100
18,Algeria,1959000000,51,0.55101
19,American Samoa,.................................................,...,0.641026
20,Andorra,9000000,121,88.6957
21,Angola,642000000,27,70.9091
22,Anguilla,2000000,136,0
23,Antigua and Barbuda,8000000,84,0
24,Argentina,3378000000,79,24.0645
25,Armenia,143000000,48,28.2361
26,Aruba,12000000,120,14.8707
27,Australia1,5386000000,231,11.8108
28,Austria,1391000000,164,72.4528
29,Azerbaijan,567000000,60,6.38434
30,Bahamas,45000000,118,0
31,Bahrain,574000000,425,0
32,Bangladesh,1625000000,10,1.96633
33,Barbados,19000000,69,0
34,Belarus,1142000000,120,0.463389
35,Belgium,2338000000,210,9.95974
36,Belize,13000000,39,64.69
37,Benin,170000000,16,0
38,Bermuda,6000000,88,0
39,Bhutan,63000000,83,100
40,Bolivia (Plurinational State of),336000000,32,31.4771
41,"Bonaire, Sint Eustatius and Saba",5000000,213,0
42,Bosnia and Herzegovina,266000000,70,41.4647
43,Botswana,86000000,39,0.131406
44,Brazil,12149000000,59,69.648
45,British Virgin Islands,2000000,85,0
...,...,...,...,...
213,Switzerland17,1113000000,136,57.7455
214,Syrian Arab Republic,542000000,28,11.5683
215,Tajikistan,106000000,13,99.7429
216,Thailand,5336000000,79,4.30519
217,The former Yugoslav Republic of Macedonia,117000000,56,26.1405
218,Timor-Leste,7000000,6,0
219,Togo,134000000,19,80.1802
220,Tonga,3000000,28,0
221,Trinidad and Tobago,824000000,611,0
222,Tunisia,430000000,39,3.49255
223,Turkey,4897000000,64,28.5367
224,Turkmenistan,1102000000,210,0
225,Turks and Caicos Islands,3000000,85,0
226,Tuvalu,.................................................,...,0
227,Uganda,452000000,12,68.0182
228,Ukraine18,4844000000,107,8.06731
229,United Arab Emirates,2710000000,300,0
230,United Kingdom of Great Britain and Northern I...,7920000000,124,10.6005
231,United Republic of Tanzania,994000000,20,31.0728
232,United States of America20,90838000000,286,11.571
233,United States Virgin Islands,.................................................,...,0
234,Uruguay,196000000,58,71.605
235,Uzbekistan,1798000000,62,21.3284
236,Vanuatu,3000000,10,14.7059
237,Venezuela (Bolivarian Republic of),2871000000,95,67.8345
238,Viet Nam,2554000000,28,45.3215
239,Wallis and Futuna Islands,0,26,0
240,Yemen,344000000,13,0
241,Zambia,400000000,26,99.7147
242,Zimbabwe,480000000,32,52.5361

In [143]:
newname = energy['Country'].replace({'Republic of Korea': 'South Korea', 'United States of America': 'United States', 'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom', 'China, Hong Kong Special Administrative Region': 'Hong Kong'})

In [144]:
def check_string(data):
    stack = []
    chars = list(data)
    for char in chars:
        for i in range(len(char)):
            reference = ['(', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
            if char[i] in reference:
                stack.append(char)
    return stack
check_string(newname)

['Australia1',
 'Bolivia (Plurinational State of)',
 'China2',
 'China, Hong Kong Special Administrative Region3',
 'China, Macao Special Administrative Region4',
 'Denmark5',
 'Falkland Islands (Malvinas)',
 'France6',
 'Greenland7',
 'Indonesia8',
 'Iran (Islamic Republic of)',
 'Italy9',
 'Japan10',
 'Japan10',
 'Kuwait11',
 'Kuwait11',
 'Micronesia (Federated States of)',
 'Netherlands12',
 'Netherlands12',
 'Portugal13',
 'Portugal13',
 'Saudi Arabia14',
 'Saudi Arabia14',
 'Serbia15',
 'Serbia15',
 'Sint Maarten (Dutch part)',
 'Spain16',
 'Spain16',
 'Switzerland17',
 'Switzerland17',
 'Ukraine18',
 'Ukraine18',
 'United Kingdom of Great Britain and Northern Ireland19',
 'United Kingdom of Great Britain and Northern Ireland19',
 'United States of America20',
 'United States of America20',
 'Venezuela (Bolivarian Republic of)']

In [145]:
newname = newname.replace({'Bolivia (Plurinational State of)': 'Bolivia', 'Falkland Islands (Malvinas)': 'Falkland Islands', 'Iran (Islamic Republic of)': 'Iran', 'Micronesia (Federated States of)': 'Micronesia', 'Sint Maarten (Dutch part)': 'Sint Maarten', 'Venezuela (Bolivarian Republic of)': 'Venezuela', 
                          'China2': 'China', 'China, Hong Kong Special Administrative Region3': 'Hong Kong', 'China, Macao Special Administrative Region4': 'Macao', 'Denmark5': 'Denmark', 'France6': 'France', 'Greenland7': 'Greenland', 'Indonesia8': 'Indonesia', 'Japan10': 'Japan', 'Kuwait11': 'Kuwait', 'Netherlands12': 'Netherlands', 
                          'Portugal13': 'Portugal', 'Saudi Arabia14': 'Saudi Arabia', 'Serbia15': 'Serbia', 'Spain16': 'Spain', 'Switzerland17': 'Switzerland', 'Ukraine18': 'Ukraine', 'United Kingdom of Great Britain and Northern Ireland19': 'United Kingdom', 'United States of America20': 'United States', 'Australia1': 'Australia', 
                          'Italy9': 'Italy'})

In [146]:
energy['Country'] = newname

In [147]:
GDP = pd.read_csv('world_bank.csv', header = 4)
GDP

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
2,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
3,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
4,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
5,Arab World,ARB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
6,United Arab Emirates,ARE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
7,Argentina,ARG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
8,Armenia,ARM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
9,American Samoa,ASM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
11,Australia,AUS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
12,Austria,AUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
13,Azerbaijan,AZE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
14,Burundi,BDI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
15,Belgium,BEL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
16,Benin,BEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
17,Burkina Faso,BFA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
18,Bangladesh,BGD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
19,Bulgaria,BGR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
20,Bahrain,BHR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
21,"Bahamas, The",BHS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
22,Bosnia and Herzegovina,BIH,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
23,Belarus,BLR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
24,Belize,BLZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
25,Bermuda,BMU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
26,Bolivia,BOL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.818838e+09,4.919069e+09,5.193073e+09,5.526504e+09,5.791476e+09,6.117247e+09,...,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,2.173110e+10,2.320795e+10,2.447524e+10,2.544488e+10
27,Brazil,BRA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.466572e+11,2.720034e+11,2.861913e+11,2.886945e+11,2.987572e+11,3.078797e+11,...,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
28,Barbados,BRB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
29,Brunei Darussalam,BRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249730e+10,1.251661e+10,1.227383e+10,1.205725e+10,1.237062e+10,1.279491e+10,1.291625e+10,1.268996e+10,1.239301e+10,1.233105e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Middle East & North Africa (IDA & IBRD countries),TMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,1.995513e+11,...,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
235,Timor-Leste,TLS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
236,Tonga,TON,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
237,South Asia (IDA & IBRD),TSA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.840484e+11,1.916061e+11,1.979559e+11,2.086032e+11,2.246484e+11,2.223897e+11,...,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
238,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.448081e+11,2.484306e+11,2.629561e+11,2.795305e+11,2.945791e+11,3.123708e+11,...,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
239,Trinidad and Tobago,TTO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.198187e+09,4.787490e+09,4.918785e+09,5.194463e+09,5.590826e+09,5.629618e+09,...,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
240,Tunisia,TUN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,5.059839e+09,...,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
241,Turkey,TUR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,8.362456e+10,8.459132e+10,8.930427e+10,9.740087e+10,1.027180e+11,1.056183e+11,...,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
242,Tuvalu,TUV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
243,Tanzania,TZA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
244,Uganda,UGA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
245,Ukraine,UKR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
246,Upper middle income,UMC,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.456839e+12,1.477022e+12,1.541565e+12,1.631063e+12,1.764693e+12,1.884705e+12,...,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
247,Uruguay,URY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.389822e+10,1.424471e+10,1.402042e+10,1.404432e+10,1.438707e+10,1.453751e+10,...,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
248,United States,USA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.078071e+12,3.148867e+12,3.340948e+12,3.487949e+12,3.690250e+12,3.926426e+12,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
249,Uzbekistan,UZB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
250,St. Vincent and the Grenadines,VCT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.418778e+08,1.483010e+08,1.537796e+08,1.441448e+08,1.494345e+08,1.507569e+08,...,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
251,"Venezuela, RB",VEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.015817e+11,1.048247e+11,1.137694e+11,1.182074e+11,1.313632e+11,1.368316e+11,...,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
252,British Virgin Islands,VGB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,Virgin Islands (U.S.),VIR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Vietnam,VNM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
255,Vanuatu,VUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
256,West Bank and Gaza,PSE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
257,World,WLD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.118678e+13,1.166806e+13,1.231357e+13,1.295118e+13,1.381212e+13,1.458038e+13,...,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
258,Samoa,WSM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
259,"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
260,South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
261,"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
262,Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
263,Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [148]:
newname2 = GDP['Country Name'].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})

In [149]:
GDP['Country Name'] = newname2

In [153]:
GDP = GDP.rename(columns = {'Country Name': 'Country'})
GDP

,Country,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
2,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
3,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
4,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
5,Arab World,ARB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
6,United Arab Emirates,ARE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
7,Argentina,ARG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
8,Armenia,ARM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
9,American Samoa,ASM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
11,Australia,AUS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
12,Austria,AUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
13,Azerbaijan,AZE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
14,Burundi,BDI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
15,Belgium,BEL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
16,Benin,BEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
17,Burkina Faso,BFA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
18,Bangladesh,BGD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
19,Bulgaria,BGR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
20,Bahrain,BHR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
21,"Bahamas, The",BHS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
22,Bosnia and Herzegovina,BIH,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
23,Belarus,BLR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
24,Belize,BLZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
25,Bermuda,BMU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
26,Bolivia,BOL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.818838e+09,4.919069e+09,5.193073e+09,5.526504e+09,5.791476e+09,6.117247e+09,...,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,2.173110e+10,2.320795e+10,2.447524e+10,2.544488e+10
27,Brazil,BRA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.466572e+11,2.720034e+11,2.861913e+11,2.886945e+11,2.987572e+11,3.078797e+11,...,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
28,Barbados,BRB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
29,Brunei Darussalam,BRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249730e+10,1.251661e+10,1.227383e+10,1.205725e+10,1.237062e+10,1.279491e+10,1.291625e+10,1.268996e+10,1.239301e+10,1.233105e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Middle East & North Africa (IDA & IBRD countries),TMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,1.995513e+11,...,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
235,Timor-Leste,TLS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
236,Tonga,TON,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
237,South Asia (IDA & IBRD),TSA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.840484e+11,1.916061e+11,1.979559e+11,2.086032e+11,2.246484e+11,2.223897e+11,...,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
238,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.448081e+11,2.484306e+11,2.629561e+11,2.795305e+11,2.945791e+11,3.123708e+11,...,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
239,Trinidad and Tobago,TTO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.198187e+09,4.787490e+09,4.918785e+09,5.194463e+09,5.590826e+09,5.629618e+09,...,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
240,Tunisia,TUN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,5.059839e+09,...,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
241,Turkey,TUR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,8.362456e+10,8.459132e+10,8.930427e+10,9.740087e+10,1.027180e+11,1.056183e+11,...,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
242,Tuvalu,TUV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
243,Tanzania,TZA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
244,Uganda,UGA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
245,Ukraine,UKR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
246,Upper middle income,UMC,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.456839e+12,1.477022e+12,1.541565e+12,1.631063e+12,1.764693e+12,1.884705e+12,...,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
247,Uruguay,URY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.389822e+10,1.424471e+10,1.402042e+10,1.404432e+10,1.438707e+10,1.453751e+10,...,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
248,United States,USA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.078071e+12,3.148867e+12,3.340948e+12,3.487949e+12,3.690250e+12,3.926426e+12,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
249,Uzbekistan,UZB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
250,St. Vincent and the Grenadines,VCT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.418778e+08,1.483010e+08,1.537796e+08,1.441448e+08,1.494345e+08,1.507569e+08,...,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
251,"Venezuela, RB",VEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.015817e+11,1.048247e+11,1.137694e+11,1.182074e+11,1.313632e+11,1.368316e+11,...,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
252,British Virgin Islands,VGB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,Virgin Islands (U.S.),VIR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Vietnam,VNM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
255,Vanuatu,VUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
256,West Bank and Gaza,PSE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
257,World,WLD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.118678e+13,1.166806e+13,1.231357e+13,1.295118e+13,1.381212e+13,1.458038e+13,...,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
258,Samoa,WSM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
259,"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
260,South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
261,"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
262,Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
263,Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [150]:
ScimEn = pd.read_excel('scimagojr-3.xlsx')
ScimEn

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
5,6,Canada,17899,17620,215003,40930,12.01,149
6,7,Germany,17027,16831,140566,27426,8.26,126
7,8,India,15005,14841,128763,37209,8.58,115
8,9,France,13153,12973,130632,28601,9.93,114
9,10,South Korea,11983,11923,114675,22595,9.57,104
10,11,Italy,10964,10794,111850,26661,10.20,106
11,12,Spain,9428,9330,123336,23964,13.08,115
12,13,Iran,8896,8819,57470,19125,6.46,72
13,14,Australia,8831,8725,90765,15606,10.28,107
14,15,Brazil,8668,8596,60702,14396,7.00,86
15,16,Taiwan,6468,6441,86099,14768,13.31,102
16,17,Turkey,5879,5827,91857,23165,15.62,104
17,18,Norway,5675,5634,32693,6024,5.76,74
18,19,Netherlands,5170,5105,48351,6067,9.35,85
19,20,Sweden,4565,4494,57889,9632,12.68,95
20,21,Malaysia,3914,3881,25545,6597,6.53,62
21,22,Switzerland,3636,3599,38962,6186,10.72,81
22,23,Denmark,3531,3494,37254,6191,10.55,85
23,24,Mexico,3249,3214,21524,4145,6.62,57
24,25,Poland,3123,3102,24852,5395,7.96,55
25,26,Saudi Arabia,2979,2930,21208,2469,7.12,61
26,27,Greece,2866,2835,41662,6226,14.54,82
27,28,Egypt,2789,2752,19123,2778,6.86,55
28,29,Belgium,2697,2642,23720,3300,8.79,63
29,30,Singapore,2488,2443,36098,3700,14.51,81
...,...,...,...,...,...,...,...,...
161,162,Greenland,3,3,49,0,16.33,2
162,163,Afghanistan,3,3,0,0,0.00,0
163,164,Cape Verde,3,3,5,0,1.67,1
164,165,French Guiana,3,3,1,1,0.33,1
165,166,Samoa,3,3,13,1,4.33,1
166,167,Cayman Islands,2,2,2,0,1.00,1
167,168,Andorra,2,2,13,0,6.50,1
168,169,Antigua and Barbuda,2,2,0,0,0.00,0
169,170,Haïti,2,2,4,1,2.00,1
170,171,Nauru,2,2,0,0,0.00,0
171,172,Seychelles,2,2,7,2,3.50,1
172,173,Mali,2,2,0,0,0.00,0
173,174,Bermuda,2,2,12,0,6.00,1
174,175,Chad,2,2,0,0,0.00,0
175,176,Burundi,2,2,23,0,11.50,1
176,177,Liberia,1,1,1,0,1.00,1
177,178,Togo,1,1,0,0,0.00,0
178,179,British Indian Ocean Territory,1,1,37,0,37.00,1
179,180,American Samoa,1,1,0,0,0.00,0
180,181,Saint Helena,1,1,1,0,1.00,1
181,182,Gibraltar,1,1,0,0,0.00,0
182,183,Maldives,1,1,1,0,1.00,1
183,184,Gambia,1,1,0,0,0.00,0
184,185,Belize,1,1,6,0,6.00,1
185,186,Palau,1,1,0,0,0.00,0
186,187,Guyana,1,1,0,0,0.00,0
187,188,Christmas Island,1,1,0,0,0.00,0
188,189,Reunion,1,1,2,1,2.00,1
189,190,Saint Lucia,1,1,0,0,0.00,0
190,191,Mauritania,1,1,1,0,1.00,1

In [184]:
def answer_one():
    keep_column = ['Country', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
    gdp = GDP[keep_column]
    sci = ScimEn.loc[0:14]
    data = pd.merge(sci, energy, how = 'left', left_on = 'Country', right_on = 'Country')
    new_data = pd.merge(data, gdp, how = 'left', left_on = 'Country', right_on = 'Country')
    new_data = new_data.set_index('Country')
    return new_data
answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.7549,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.571,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.2328,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.6005,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.2887,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.9454,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.9015,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.9691,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.0203,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.27935,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.6672,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.9686,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.70772,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.8108,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.648,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [185]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [562]:
def answer_two():
    data = pd.merge(GDP, energy, how = 'inner', left_on = 'Country', right_on = 'Country')
    new_data = pd.merge(data, ScimEn.loc[0:14], how = 'inner', left_on = 'Country', right_on = 'Country')
    row = data.shape[0]-15
    return row
answer_two()

171

<br>

Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [195]:
def answer_three():
    Top15 = answer_one()
    top = Top15[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
    Top15_mean = top.mean(axis = 1).sort_values(ascending = False)
    avgGDP = pd.Series(Top15_mean)
    return avgGDP
answer_three()

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [534]:
def answer_four():
    Top15 = answer_one()
    change = Top15['2015'] - Top15['2006']
    change = change.sort_values(ascending = False)
    return change.loc['United Kingdom']
answer_four()

246702696075.3999

### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*

In [213]:
def answer_five():
    Top15 = answer_one()[['Energy Supply per Capita']]
    supply_avg = Top15.mean(axis = 0)
    return supply_avg['Energy Supply per Capita']
answer_five()

157.6

### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [295]:
def answer_six():
    Top15 = answer_one()[['% Renewable']]
    maximum = Top15.sort_values('% Renewable',ascending = False)
    return print(maximum.index[0]+' '+str(maximum.iloc[0][0]))
answer_six()

Brazil 69.64803

### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [277]:
def answer_seven():
    Top15 = answer_one()
    df = Top15[['Self-citations','Citations']]
    ratio = Top15['Self-citations']/Top15['Citations']
    maximum = ratio.sort_values(ascending = False)
    return print(maximum.index[0] +' '+ str(maximum[0]))
answer_seven()

China 0.6893126179389422

### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [520]:
def answer_eight():
    Top15 = answer_one()
    pop = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    maximum = pop.sort_values(ascending = False)
    return print(maximum.index[0])
answer_eight()

China

### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [551]:
def answer_nine():
    Top15 = answer_one()
    Top15['pop'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['pop']
    correlation = Top15['Energy Supply per Capita'].astype('float').corr(Top15['Citable docs per Capita'].astype('float'))
    return correlation
answer_nine()

0.7940010435442947

In [552]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [553]:
plot9() # Be sure to comment out plot9() before submitting the assignment!

ValueError: scatter requires x column to be numeric

### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [345]:
renew = []
def fun(data, column, mid):
    for i in range(len(data)):
        if data.iloc[i][column] >= mid:
            renew.append(1) 
        else:
            renew.append(0)
    return renew
def answer_ten():
    Top15 = answer_one()
    middle = np.median(Top15['% Renewable'])
    Top15['HighRenew'] = fun(Top15, '% Renewable', middle)
    return pd.Series(Top15['HighRenew'])
answer_ten()

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int64

### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [393]:
def answer_eleven():
    Top15 = answer_one()
    Continent = pd.DataFrame([{'Country': 'China', 'Continent': 'Asia'}, {'Country': 'United States' , 'Continent': 'North America'}, {'Country': 'Japan', 'Continent': 'Asia'}, {'Country': 'United Kingdom', 'Continent': 'Europe'},
                             {'Country': 'Russian Federation', 'Continent': 'Europe'}, {'Country': 'Canada', 'Continent': 'North America'}, {'Country': 'Germany', 'Continent': 'Europe'}, {'Country': 'India', 'Continent': 'Asia'}, 
                             {'Country': 'France', 'Continent': 'Europe'}, {'Country': 'South Korea', 'Continent': 'Asia'}, {'Country': 'Italy', 'Continent': 'Europe'}, {'Country': 'Spain', 'Continent': 'Europe'}, 
                             {'Country': 'Iran', 'Continent': 'Asia'}, {'Country': 'Australia', 'Continent': 'Australia'}, {'Country': 'Brazil', 'Continent': 'South America'}])
    Continent = Continent.set_index('Country')
    new = pd.merge(Continent, Top15, how = 'left', right_on = Top15.index, left_on = Continent.index)
    new['pop'] = new['Energy Supply']/new['Energy Supply per Capita']
    new = new[['Continent', 'pop']].set_index('Continent')
    new = pd.DataFrame(new, dtype = 'float').groupby(level = 0)['pop'].agg({'size': np.size, 'sum': np.sum, 'mean': np.average, 'std': np.std})
    return new
answer_eleven()

C:\Users\zubad\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  # This is added back by InteractiveShellApp.init_path()

               size           sum          mean           std
Continent
Asia            5.0  2.898666e+09  5.797333e+08  6.790979e+08
Australia       1.0  2.331602e+07  2.331602e+07           NaN
Europe          6.0  4.579297e+08  7.632161e+07  3.464767e+07
North America   2.0  3.528552e+08  1.764276e+08  1.996696e+08
South America   1.0  2.059153e+08  2.059153e+08           NaN

### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [517]:
def answer_twelve():
    Top15 = answer_one()
    Continent = pd.DataFrame([{'Country': 'China', 'Continent': 'Asia'}, {'Country': 'United States' , 'Continent': 'North America'}, {'Country': 'Japan', 'Continent': 'Asia'}, {'Country': 'United Kingdom', 'Continent': 'Europe'},
                             {'Country': 'Russian Federation', 'Continent': 'Europe'}, {'Country': 'Canada', 'Continent': 'North America'}, {'Country': 'Germany', 'Continent': 'Europe'}, {'Country': 'India', 'Continent': 'Asia'}, 
                             {'Country': 'France', 'Continent': 'Europe'}, {'Country': 'South Korea', 'Continent': 'Asia'}, {'Country': 'Italy', 'Continent': 'Europe'}, {'Country': 'Spain', 'Continent': 'Europe'}, 
                             {'Country': 'Iran', 'Continent': 'Asia'}, {'Country': 'Australia', 'Continent': 'Australia'}, {'Country': 'Brazil', 'Continent': 'South America'}])
    Continent = Continent.set_index('Country')
    new = pd.merge(Continent, Top15, how = 'left', right_on = Top15.index, left_on = Continent.index)
    new['group'] = pd.cut(new['% Renewable'], bins = 5)
    cut_new = new[['key_0', 'Continent', 'group']].rename(columns = {'key_0': 'Country'}).set_index(['Continent', 'group']).groupby(['Continent','group'])['Country'].size()
    #cut_new = pd.Series(cut_new['Country'], index = cut_new.index)
    return cut_new
answer_twelve()

Continent      group
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
Name: Country, dtype: int64

### Question 13 (6.6%)
Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

e.g. 317615384.61538464 -> 317,615,384.61538464

*This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*

In [500]:
def answer_thirteen():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    new = Top15['PopEst']
    form = []
    for i in range(15):
        form.append('{:,}'.format(new.iloc[i]))
    form = pd.Series(form)
    index = pd.Series(new.index)
    PopEst = pd.concat([index, form], axis = 1).set_index('Country').rename(columns = {0: 'PopEst'})
    PopEst = pd.Series(PopEst['PopEst'], index = PopEst.index)
    return PopEst
answer_thirteen()

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: PopEst, dtype: object

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [ ]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")

In [ ]:
#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!